### ISSUE TITLE
Waypoint done by the planner are not saved

### ISSUE THREAD

**Issue by morrtz** [jboecker/dcs-mission-planner#26]
I've done some tests and it seems that new instances I create and then go into one side and add WPs will not save the new waypoints when I save the mission.

Reproduce:
1. Create new instance from a mission file. (I Created Allies only ground forces view)
2. Copy the Links that are created and close the Admin Tool window. (If the windows is kept open and I do not need to reload the mission file, the issue does not reproduce).
3. Change WPs on one of the sides links.
4. Go back to the Admin Tool and enter the existing instance admin link.
5. Upload the save mission file.
6. Save the new updated mission.
7. Opened in mission editor, WPs not updated.

**Comment by jboecker** [comment]
Should be fixed in master now. I can't test it because I am on my laptop, but since it's a one-line fix I am pretty confident :)
