### ISSUE TITLE
Ability to assign skin to selected aircraft

### ISSUE THREAD

**Issue by HomeFries94** [jboecker/dcs-mission-planner#8]
I know this is a bit more involved because it involves parsing the liveries folders, but this could be great for virtual squadrons as this way they could add their own personalized aircraft without requiring custom missions or slots for every conceivable member.

Ideal solution would be to parse the liveries folders (both dcs world and saved games), and list the skins based on the type of aircraft, but a workable solution would be the files common dialog that selects the folder of the decription.ini we manually select.

**Comment by jboecker** [comment]
Changing the skin of an aircraft in a mission file seems to be as easy as setting the "livery_id" field of the unit.

Because the mission planner runs in a browser, file system access is limited to files that are explicitly selected by the user for obvious security reasons.

I would suggest to write a separate tool that does the following:
- Find the DCS installation by looking at the registry
- Scan the liveries folder to generate a list of all possible livery IDs for every aircraft type
- Given the instance ID and admin password, upload the list in JSON format using a simple HTTP request

If someone else were to write such a tool, I'd be willing to do the neccessary modifications to the mission planner (i.e. when information about livery ids is available, show a dropdown box to change the skin).

**Comment by HomeFries94** [comment]
That makes sense, and having the skin list tied to admin works because if he doesn't have the skin it won't display in the first place.

I would also add after finding the DCS installation via registry that the c:\users\%username%\Saved Games\DCS\liveries folder tree is parsed as well.

I'll see what I can do about the routine.  Is there any specific language or hooks you require?

**Comment by jboecker** [comment]
The final interaction step with the mission planner would look like this:
- Put your mapping of aircraft type to livery list and the admin password into a request in JSON format, which would look like this:

```
{
    "instance_id": "abcd",
    "admin_pw":"xkcd",
    "liveries": {
        "A-10C": ["23rd TFW England AFB (EL)", "104th FS Maryland ANG, Baltimore (MD)"],
        "P-51D": ["Dogfight Blue", "USAF 302rd FS, RED TAILS"]
    }
}
```
- Make a HTTP POST request to, say, https://dcs-mission-planner.herokuapp.com/set_livery_list/ with your JSON request in the body.

You can use pretty much any language you want, as they all can speak HTTP and have a JSON library available.

**Comment by HomeFries94** [comment]
I have no experience with HTTP requests or JSON, but here is some VBScript that should provide the 95% solution:

```
 dim dcsfolder ,userfolder, livery_dcs, livery_user, output_text , i
 dim ObjectList(), LiveryList() 
 dim fs
 dim fsout  'can be removed if no text file generated
 Dim WSHShell,WshSysEnv

 Set WSHShell = CreateObject("WScript.Shell")
 Set WshSysEnv = WshShell.Environment("PROCESS")
 set fs = CreateObject("Scripting.FileSystemObject")

 'livery folders are dcsfolder & livery_dcs and userfolder & livery_user
 livery_dcs = "\bazar\liveries"
 livery_user = "\Saved Games\DCS\Liveries"

 dcsfolder = readFromRegistry("HKEY_CURRENT_USER\Software\Eagle Dynamics\DCS World\Path","c:\program files (x86)\Eagle Dynamics\DCS World") 'no trailing backslash
 userfolder = WshSysEnv("USERPROFILE") 'no trailing backslash


 GetObjectsList(dcsfolder & livery_dcs) 'gets names of aircraft and objects in default liveries folder
 redim LiveryList(ubound(ObjectList))   'redim livery list to number of objects so that they match up

 for i = 0 to ubound(ObjectList)            'assign all liveries to objects 
    if ObjectList(i) <> "" then 
        LiveryList(i) = chr(34) & ObjectList(i) & chr(34) & ": [" 
        LiveryList(i) = LiveryList(i) & GetLiveries(dcsfolder & livery_dcs & "\" & ObjectList(i)) 
        if fs.FolderExists(userfolder & livery_user & "\" & ObjectList(i)) then LiveryList(i) = LiveryList(i) & GetLiveries(userfolder & livery_user & "\" & ObjectList(i) )
        LiveryList(i) = LiveryList(i) & "]"
    end if
 Next

 'format output for query
 output_text = chr(34) & "liveries" & chr(34) & ": {" & vbcrlf      'additional leading text like admin password can precede this line
 for i = 0 to ubound(LiveryList)-1  'one less than ubound for trailing comma
    output_text = output_text & vbtab & LiveryList(i) & ", " & vbcrlf
 Next
 output_text = output_text & LiveryList(ubound(LiveryList)) & vbcrlf & vbtab & "}"  'last line closes out bracket and can close out more depending on leading text

 'just for test output; can be removed or set to something else
 set fsout = fs.CreateTextFile(userfolder & "\Saved Games\DCS\all_liveries.txt", true,true) 
 fsout.Write (output_text)
 fsout.Close
 'end test output

 'close out
 set fs = nothing
 set WSHShell = nothing


 'Subs and Functions:

 Sub GetObjectsList(folderspec)
    Dim  f, f1, fc, s, i
    Set f = fs.GetFolder(folderspec)
    Set fc = f.SubFolders
    i = 0
    For Each f1 in fc
        redim preserve Objectlist(i+1)
        ObjectList(i) = f1.name 
        i = i+1
    Next
 End Sub

 function GetLiveries(folderspec)
    Dim f, f1, fc, s
    Set f = fs.GetFolder(folderspec)
    Set fc = f.SubFolders
    For Each f1 in fc
        s =  s & chr(34) & f1.name & chr(34) & ", "
    Next
    GetLiveries = s
 End function

 function readFromRegistry (strRegistryKey, strDefault )
    Dim value
    On Error Resume Next
    value = WSHShell.RegRead( strRegistryKey )

    if err.number <> 0 then
        readFromRegistry= strDefault
    else
        readFromRegistry=value
    end if

 end function
```

**Comment by jboecker** [comment]
I just took a closer look at this. All that seems to be missing is the HTTP request, which [seems to be pretty easy to do using the XmlHttp object](http://www.paulsadowski.com/wsh/xmlhttp.htm).

I will add it when I get around to implement the backend part (I want to fix #11 first).

**Comment by jboecker** [comment]
I have added the required mission planner functionality.

I have decided against having the script upload the livery, because (a) there does not seem to be an easy way to do either HTTP Basic Authentication or WebSockets in VBS and (b) you'd probably want to manually edit the list anyway to limit the options to a few interesting choices.

You can now upload a text file with the JSON-formatted livery list from the admin tool.

Btw, your script does not output valid JSON: you cannot have a comma at the end of a list.
- Invalid: `["foo", "bar", "baz",]`
- Valid: `["foo", "bar", "baz"]`

Also, get rid of the "liveries": prefix.

Here's an example of a valid input file that I used for testing:

```
{
    "A-10C": ["104th FS Maryland ANG, Baltimore (MD)", "118th FS Bradley ANGB, Connecticut (CT)", "118th FS Bradley ANGB, Connecticut (CT) N621", "172nd FS Battle Creek ANGB, Michigan (BC)", "184th FS Arkansas ANG, Fort Smith (FS)", "190th FS Boise ANGB, Idaho (ID)", "23rd TFW England AFB (EL)", "25th FS Osan AB, Korea (OS)", "354th FS Davis Monthan AFB, Arizona (DM)", "355th FS Eielson AFB, Alaska (AK)", "357th FS Davis Monthan AFB, Arizona (DM)", "358th FS Davis Monthan AFB, Arizona (DM)", "422nd TES Nellis AFB, Nevada (OT)", "47th FS Barksdale AFB, Louisiana (BD)", "66th WS Nellis AFB, Nevada (WA)", "74th FS Moody AFB, Georgia (FT)", "81st FS Spangdahlem AB, Germany (SP) 1", "81st FS Spangdahlem AB, Germany (SP) 2", "A-10 Grey", "Australia Notional RAAF", "Canada RCAF 409 Squadron", "Canada RCAF 442 Snow Scheme", "Fictional Canadian Air Force Pixel Camo", "Fictional France Escadron de Chasse 03.003 ARDENNES", "Fictional Georgian Grey", "Fictional Georgian Olive", "Fictional German 3322", "Fictional German 3323", "Fictional Israel 115 Sqn Flying Dragon", "Fictional Italian AM (23Gruppo)", "Fictional Royal Norwegian Air Force", "Fictional Russian Air Force 1", "Fictional Russian Air Force 2", "Fictional Spanish 12nd Wing", "Fictional Spanish AGA", "Fictional Spanish Tritonal", "Fictional Ukraine Air Force 1" ], 
    "F-15C": ["106th SQN (8th Airbase)", "19th Fighter SQN (AK)", "390th Fighter SQN", "493rd Fighter SQN (LN)", "58th Fighter SQN (EG)", "65th Agressor SQN (WA) Flanker", "65th Agressor SQN (WA) MiG", "65th Agressor SQN (WA) SUPER_Flanker", "Ferris Scheme" ], 
    "F-15E": ["335th Fighter SQN (SJ)", "492d Fighter SQN (LN)", "IDF No 69 Hammers Squadron" ], 
    "ka-50": ["Abkhazia 1", "belgium camo", "belgium olive", "belgium sar", "canadian forces", "denmark camo", "Denmark navy trainer", "France Armee de Terre 1", "France Armee de Terre 2", "France Armee de Terre Desert", "georgia camo", "german 8320", "german 8332", "Israel IAF camo 1", "Israel IAF camo 2", "Israel IAF camo 3", "Italy Aeronautica Militare", "Italy Esercito Italiano", "Netherlands RNAF", "Netherlands RNAF wooded", "norway camo", "Russia Demo #024", "Russia Demo #22 `Black Shark`", "Russia Demo `Werewolf`", "Russia DOSAAF", "Russia fictional desert scheme", "Russia Fictional Olive Grey", "Russia Fictional Snow Splatter", "Russia Fictional Swedish", "Russia Fictional Tropic Green", "Russia New Year", "Russia Standard Army", "Russia Standard Army (Worn)", "Russia Worn Black", "South Ossetia 1", "Spain SAA Arido", "Spain SAA Boscoso", "Spain SAA Standard", "Turkey Fictional", "Turkey Fictional 1", "Turkey fictional desert scheme", "Turkey Fictional Light Gray", "uk camo", "ukraine camo 1", "ukraine camo 1 dirt", "Ukraine Demo", "us army", "us marines 1", "us marines 2" ],
    "su-25": ["Abkhazian Air Force", "broken camo scheme #1 (native). 299th oshap", "broken camo scheme #2 (native). 452th shap", "field camo scheme #1 (native)", "field camo scheme #1 (native)01", "field camo scheme #2 (native). 960th shap", "field camo scheme #3 (worn-out). 960th shap", "forest camo scheme #1 (native)", "petal camo scheme #1 (native). 299th brigade", "petal camo scheme #2 (native). 299th brigade", "`scorpion` demo scheme (native)" ], 
    "su-25t": ["af standard", "af standard 1", "af standard 101", "af standard 2", "su-25t test scheme" ], 
    "su-25tm": ["Flight Research Institute  VVS"]
    }
```

**Comment by HomeFries94** [comment]
I revised the VB script to conform to your format and added the command line abilities to parse the openbeta version of DCS and create your own filename if you choose.  However, it appears that whether the skins are listed on the web page is determined by the case of the livery folders.  For example, the A-10A, A-10C, F-15C, and P-51D all display their full list of liveries, whereas the lowercase ka-50, mig-29 (all variants), su-27, su-33, su-25, su-25t, and uh-1h only display the skin listed in the mission.

The big question is whether it's easier to make the mission editor case insensitive, or whether I should force uppercase for ObjectList().  Once we get this ironed out I'll upload the script either here (for inclusion into the program) or separately to the ED thread.

**Comment by jboecker** [comment]
It's easy to fix in the mission planner (just convert everything to uppercase when uploading the livery list and convert the unittype field to uppercase before the lookup).

**Comment by jboecker** [comment]
I have pushed a fix to the master branch, but I cannot test it right now because I am not at my gaming rig. You can go to https://github.com/jboecker/dcs-mission-planner and click the "Download ZIP" button on the right to get a ZIP archive of the current master branch.

**Comment by HomeFries94** [comment]
I confirm that the fix works on the master branch.  I was able to change the uppercase and lowercase aircraft and the changes took in the mission (tested: uh-1h and P-51D).  Also confirmed that skin swap works with skins that have names in the description.lua that differ from the folder name.

**Comment by HomeFries94** [comment]
How would you like the VB script?  Would you like the text here, or would you prefer an upload to the ED thread?

**Comment by jboecker** [comment]
Ideally as a pull request on GitHub :)
Commit the file to the "scripts" subfolder of your fork of the repository and add a descriptive commit message, e.g.

```
add scripts/make-livery-list.vbs to a generate livery list ready for upload to an instance
```

You can then create a pull request on GitHub, which I can accept with minimal effort (and you are automatically credited in the "committer" field).

If you don't want to bother to learn git just for one contribution, you can also paste it here.

**Comment by HomeFries94** [comment]
Done.  Wasn't that hard to figure out.
